In [1]:
import numpy as np

print("NumPy version:", np.__version__)

NumPy version: 2.5.2

In [2]:
import pandas as pd

In [3]:
df = pd.read_csv("dataset/IMDB Dataset.csv")
df.head()

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [4]:
print(df.shape)
print(df.columns)

(50000, 2)
Index(['review', 'sentiment'], dtype='str')

In [5]:
df.sentiment.value_counts()

sentiment
positive    25000
negative    25000
Name: count, dtype: int64

In [6]:
df.isnull().sum()

review       0
sentiment    0
dtype: int64

In [7]:
df.sentiment=df.sentiment.map({"negative":0,"positive":1})
df.head()

                                              review  sentiment
0  One of the other reviewers has mentioned that ...          1
1  A wonderful little production. <br /><br />The...          1
2  I thought this was a wonderful way to spend ti...          1
3  Basically there's a family where a little boy ...          0
4  Petter Mattei's "Love in the Time of Money" is...          1

In [8]:
review1=df.review.iloc[0]
words=review1.lower().split()

print(words[:20])
print("Total words:", len(words))

['one', 'of', 'the', 'other', 'reviewers', 'has', 'mentioned', 'that', 'after', 'watching', 'just', '1', 'oz', 'episode', "you'll", 'be', 'hooked.', 'they', 'are', 'right,']
Total words: 307

In [9]:
word_counts={}

for review in df.review :
    words=review.lower().split()
    for word in words :
        if word in word_counts:
            word_counts[word]+=1
        else:
            word_counts[word]=1

print(list(word_counts.items())[:10]) ## dictionary does not support slicing so convert it into a list first & item make the pair as a tuple

[('one', 44983), ('of', 286661), ('the', 638861), ('other', 16373), ('reviewers', 418), ('has', 32610), ('mentioned', 810), ('that', 130140), ('after', 13948), ('watching', 8146)]

In [10]:
print(f"total unique wrds: {len(word_counts)}")

total unique wrds: 390931

In [11]:
unique_once=0
for word in word_counts:
    if word_counts[word]==1:
        unique_once+=1
print(unique_once)

237310

In [12]:
## Sorting the dictionary 

sorted_word_counts=sorted(word_counts.items(),key=lambda item :item[1],reverse=True)
print(sorted_word_counts[:50])

word_df=pd.DataFrame(sorted_word_counts,columns=["word","count"])

[('the', 638861), ('a', 316615), ('and', 313637), ('of', 286661), ('to', 264573), ('is', 204876), ('in', 179807), ('i', 141587), ('this', 138483), ('that', 130140), ('it', 129614), ('/><br', 100974), ('was', 93258), ('as', 88242), ('with', 84590), ('for', 84510), ('but', 77864), ('on', 62890), ('movie', 61492), ('are', 57009), ('his', 56870), ('not', 56765), ('you', 55600), ('film', 55086), ('have', 54423), ('he', 51062), ('be', 50901), ('at', 45259), ('one', 44983), ('by', 43359), ('an', 42330), ('they', 40860), ('from', 39322), ('all', 38570), ('who', 38326), ('like', 37281), ('so', 35972), ('just', 34259), ('or', 33300), ('has', 32610), ('about', 32398), ('her', 31244), ("it's", 31212), ('if', 30794), ('some', 30165), ('out', 28980), ('what', 28008), ('very', 26908), ('when', 26904), ('there', 26079)]

In [13]:
word_df.head(10)

   word   count
0   the  638861
1     a  316615
2   and  313637
3    of  286661
4    to  264573
5    is  204876
6    in  179807
7     i  141587
8  this  138483
9  that  130140

In [14]:
word_df.shape

(390931, 2)

In [15]:
## Taking vocab size of only 10000

In [16]:
top_words_df=word_df.head(10000)

print(f"Vocabulary size : {len(top_words_df)}")
print(top_words_df.head())
print(top_words_df.tail())

Vocabulary size : 10000
  word   count
0  the  638861
1    a  316615
2  and  313637
3   of  286661
4   to  264573
              word  count
9995      absorbed     69
9996      frontier     69
9997  representing     69
9998        paris.     69
9999       worked.     69

In [17]:
top_words_df["Token ID"]=range(1,len(top_words_df)+1)
print(top_words_df.head(10))
print(top_words_df.tail(10))

   word   count  Token ID
0   the  638861         1
1     a  316615         2
2   and  313637         3
3    of  286661         4
4    to  264573         5
5    is  204876         6
6    in  179807         7
7     i  141587         8
8  this  138483         9
9  that  130140        10
              word  count  Token ID
9990    consisting     69      9991
9991       shuttle     69      9992
9992      charlton     69      9993
9993         cecil     69      9994
9994       leader,     69      9995
9995      absorbed     69      9996
9996      frontier     69      9997
9997  representing     69      9998
9998        paris.     69      9999
9999       worked.     69     10000

In [18]:
word_to_id = {}

for i in range(len(top_words_df)):
    word = top_words_df.iloc[i]["word"]
    token_id = top_words_df.iloc[i]["Token ID"]

    word_to_id[word] = token_id

print(list(word_to_id.items())[:10])
print("Total words:", len(word_to_id))

[('the', np.int64(1)), ('a', np.int64(2)), ('and', np.int64(3)), ('of', np.int64(4)), ('to', np.int64(5)), ('is', np.int64(6)), ('in', np.int64(7)), ('i', np.int64(8)), ('this', np.int64(9)), ('that', np.int64(10))]
Total words: 10000

In [19]:
from sklearn.model_selection import train_test_split

In [20]:
train_df,temp_df=train_test_split(df,test_size=0.2,random_state=42,stratify=df["sentiment"])
val_df, test_df=train_test_split(temp_df,test_size=0.5,random_state=42,stratify=temp_df['sentiment'])

print("Training set:", train_df.shape)
print("Validation set:", val_df.shape)
print("Test set:", test_df.shape)

Training set: (40000, 2)
Validation set: (5000, 2)
Test set: (5000, 2)

In [21]:
X_train = train_df["review"]
y_train = train_df["sentiment"]

X_val = val_df["review"]
y_val = val_df["sentiment"]

X_test = test_df["review"]
y_test = test_df["sentiment"]

print("Training:", len(X_train), len(y_train))
print("Validation:", len(X_val), len(y_val))
print("Test:", len(X_test), len(y_test))

Training: 40000 40000
Validation: 5000 5000
Test: 5000 5000

In [22]:
## Doing all this for training Data frame

In [23]:
word_counts = {}

for review in X_train:
    words = review.lower().split()

    for word in words:
        if word in word_counts:
            word_counts[word] += 1
        else:
            word_counts[word] = 1

print("Unique words:", len(word_counts))

Unique words: 339686

In [24]:
sorted_words = sorted(
    word_counts.items(),
    key=lambda item: item[1],
    reverse=True
)

In [25]:
top_words_df = pd.DataFrame(
    sorted_words[:10000],
    columns=["word", "count"]
)

top_words_df["Token ID"] = range(
    1, len(top_words_df) + 1
)

print(top_words_df.head(10))
print("Vocabulary size:", len(top_words_df))

   word   count  Token ID
0   the  511759         1
1     a  253641         2
2   and  251160         3
3    of  229540         4
4    to  212085         5
5    is  163737         6
6    in  144054         7
7     i  113889         8
8  this  111137         9
9  that  104277        10
Vocabulary size: 10000

In [26]:
word_to_id = {}

for i in range(len(top_words_df)):
    word = top_words_df.iloc[i]["word"]
    token_id = top_words_df.iloc[i]["Token ID"]

    word_to_id[word] = token_id

print("Dictionary size:", len(word_to_id))
print(list(word_to_id.items())[:10])

Dictionary size: 10000
[('the', np.int64(1)), ('a', np.int64(2)), ('and', np.int64(3)), ('of', np.int64(4)), ('to', np.int64(5)), ('is', np.int64(6)), ('in', np.int64(7)), ('i', np.int64(8)), ('this', np.int64(9)), ('that', np.int64(10))]

In [27]:
PAD_ID = 0 #fills shorter reviews to a fixed length.
UNK_ID = 10001 ## represents words outside our 10,000-word vocabulary.

In [28]:
def review_to_ids(review):
    words=review.lower().split()
    token_ids=[]

    for word in words :
        if word in word_to_id:
            token_ids.append(word_to_id[word])
        else:
            token_ids.append(UNK_ID)
    return token_ids

In [29]:
print("Original review:")
print(X_train.iloc[0][:20])

Original review:
I caught this little

In [30]:
## Now testing it on one review 

print(review_to_ids(X_train.iloc[0][:20]))

[np.int64(8), np.int64(1014), np.int64(9), np.int64(106)]

In [31]:
X_train_ids=[]

for review in X_train:
    token_ids=review_to_ids(review)
    X_train_ids.append(token_ids)

print("Total reviews:", len(X_train_ids))
print("First review token IDs:", X_train_ids[0][:20])
print("First review length:", len(X_train_ids[0]))

Total reviews: 40000
First review token IDs: [np.int64(8), np.int64(1014), np.int64(9), np.int64(106), np.int64(2219), np.int64(393), np.int64(30), np.int64(2410), np.int64(153), np.int64(7), np.int64(9142), np.int64(39), 10001, np.int64(8), np.int64(13), np.int64(28), np.int64(2), 10001, np.int64(2160), np.int64(5)]
First review length: 161

In [32]:
## Restricting every review to 100 words max and padding words with length less than 100 words 

Max_len=100

X_train_padded = []

for token_ids in X_train_ids:
    if len(token_ids) > Max_len:
        token_ids = token_ids[:Max_len]
    else:
        while len(token_ids) < Max_len:
            token_ids.append(PAD_ID)

    X_train_padded.append(token_ids)

print("Total reviews:", len(X_train_padded))
print("First review:", X_train_padded[0])
print("First review length:", len(X_train_padded[0]))

Total reviews: 40000
First review: [np.int64(8), np.int64(1014), np.int64(9), np.int64(106), np.int64(2219), np.int64(393), np.int64(30), np.int64(2410), np.int64(153), np.int64(7), np.int64(9142), np.int64(39), 10001, np.int64(8), np.int64(13), np.int64(28), np.int64(2), 10001, np.int64(2160), np.int64(5), np.int64(65), np.int64(102), np.int64(174), np.int64(772), np.int64(1016), np.int64(559), np.int64(1), np.int64(2160), np.int64(13), np.int64(3698), np.int64(335), np.int64(3), np.int64(1663), np.int64(59), 10001, np.int64(32), np.int64(1162), np.int64(2), np.int64(711), np.int64(4), np.int64(1016), np.int64(384), 10001, np.int64(4045), np.int64(71), np.int64(190), np.int64(7), np.int64(1), 10001, np.int64(76), np.int64(66), np.int64(587), np.int64(1437), np.int64(17), np.int64(9), np.int64(323), np.int64(18), np.int64(482), np.int64(710), 10001, np.int64(1), np.int64(356), np.int64(13), np.int64(7), 10001, np.int64(1), np.int64(1020), np.int64(517), np.int64(323), np.int64(48), np.int64(32), np.int64(1162), 10001, 10001, np.int64(248), np.int64(563), 10001, 10001, np.int64(345), np.int64(4), np.int64(1596), np.int64(18), np.int64(43), np.int64(2984), np.int64(56), np.int64(263), np.int64(28), np.int64(1), np.int64(3765), np.int64(349), np.int64(2), np.int64(4220), np.int64(2461), np.int64(3), 10001, np.int64(10), np.int64(95), np.int64(11), np.int64(53), 10001]
First review length: 100

In [33]:

# Convert validation reviews into token IDs using the existing vocabulary
X_val_ids = []

for review in X_val:

    # Convert the review into lowercase words
    words = review.lower().split()

    # Convert each word into its ID using the training vocabulary
    token_ids = [
        word_to_id.get(word, UNK_ID)
        for word in words
    ]

    X_val_ids.append(token_ids)


# Keep every review at a maximum length of 100 tokens
# Pad shorter reviews with PAD_ID, just like the training data
X_val_padded = []

for token_ids in X_val_ids:

    if len(token_ids) > Max_len:
        token_ids = token_ids[:Max_len]

    else:
        while len(token_ids) < Max_len:
            token_ids.append(PAD_ID)

    X_val_padded.append(token_ids)


# Convert the padded reviews into a NumPy array
X_val_array = np.array(X_val_padded, dtype=np.int64)

print("Validation shape:", X_val_array.shape)
print("First validation review length:", len(X_val_array[0]))

Validation shape: (5000, 100)
First validation review length: 100

In [34]:
y_train = y_train.map({
    "negative": 0,
    "positive": 1
})

In [35]:
X_train_array = np.array(X_train_padded, dtype=np.int64)
y_train_array = np.array(y_train, dtype=np.int64)

print("X shape:", X_train_array.shape)
print("y shape:", y_train_array.shape)
print("X data type:", X_train_array.dtype)
print("y data type:", y_train_array.dtype)

X shape: (40000, 100)
y shape: (40000,)
X data type: int64
y data type: int64

C:\Users\HP\AppData\Roaming\Python\Python313\site-packages\pandas\core\series.py:901: RuntimeWarning: invalid value encountered in cast
  arr = np.array(values, dtype=dtype, copy=copy)

In [36]:
# Check if we already have the padded validation reviews
print(type(X_val))
print(X_val.shape if hasattr(X_val, "shape") else len(X_val))

<class 'pandas.Series'>
(5000,)

In [37]:
print("X_train_array:", X_train_array.shape)
print("y_train_array:", y_train_array.shape)

print("First 10 labels:", y_train_array[:10])
print("Unique labels:", np.unique(y_train_array))

X_train_array: (40000, 100)
y_train_array: (40000,)
First 10 labels: [-9223372036854775808 -9223372036854775808 -9223372036854775808
 -9223372036854775808 -9223372036854775808 -9223372036854775808
 -9223372036854775808 -9223372036854775808 -9223372036854775808
 -9223372036854775808]
Unique labels: [-9223372036854775808]

In [38]:
## intialize the embedding vector

In [39]:
embedding_size=32
vocab_size=10002

E=np.random.randn(vocab_size,embedding_size)*0.1

E[0]=0

print(f"Embedding matrix shape : {E.shape}")
print(f"Embedding of token ID 8 : {E[8]}")

Embedding matrix shape : (10002, 32)
Embedding of token ID 8 : [-0.04771042  0.13917194  0.05207826 -0.0232853   0.08480625  0.05073595
  0.0830139  -0.03026337 -0.08575813 -0.01049999  0.16397005 -0.13157791
  0.05109439  0.24669228  0.07301859 -0.07158949  0.12256357 -0.0438704
  0.18951176  0.01137245 -0.05298262  0.04498917  0.2225679   0.23088334
 -0.0877872  -0.00094792  0.07702191 -0.07488564  0.1914623  -0.07348689
 -0.03440419  0.00929127]

In [40]:
token_ids = [8, 1014, 9, 106]

review_embeddings = E[token_ids]

print("Shape:", review_embeddings.shape)
print(review_embeddings)

Shape: (4, 32)
[[-0.04771042  0.13917194  0.05207826 -0.0232853   0.08480625  0.05073595
   0.0830139  -0.03026337 -0.08575813 -0.01049999  0.16397005 -0.13157791
   0.05109439  0.24669228  0.07301859 -0.07158949  0.12256357 -0.0438704
   0.18951176  0.01137245 -0.05298262  0.04498917  0.2225679   0.23088334
  -0.0877872  -0.00094792  0.07702191 -0.07488564  0.1914623  -0.07348689
  -0.03440419  0.00929127]
 [ 0.02664988 -0.10965866 -0.08032249  0.19681332 -0.04771782 -0.00958268
  -0.02303845  0.02902006 -0.05874851  0.00916764  0.0755721  -0.00800245
   0.08503272 -0.07320636 -0.23464403  0.0357026  -0.08682975  0.21633499
   0.1045919   0.09403896 -0.13556622 -0.15866037 -0.0104426  -0.07864693
  -0.04131985  0.04266265  0.0573548  -0.26008392 -0.01946808 -0.10755162
  -0.01726272 -0.09913689]
 [-0.03129178 -0.02641255  0.13371416  0.02130618 -0.07062664  0.14275783
  -0.05855725 -0.02841322 -0.10520859  0.048775   -0.03029391  0.04201002
  -0.08845585 -0.05353283  0.00356204  0.1763471  -0.02985914 -0.05985867
  -0.03556862  0.07702237  0.07302968  0.2003359   0.01276158 -0.0941267
  -0.10370269  0.03744389  0.02602946  0.00515755  0.14214297 -0.10245318
  -0.08579858  0.02515909]
 [ 0.0259603  -0.03067631  0.01395734  0.05404447  0.00667728  0.11240441
  -0.11567746  0.08690724  0.07029631 -0.03995593  0.03515008  0.0122588
   0.05532073 -0.0177794  -0.14859662 -0.02499845  0.07267147 -0.00469229
  -0.14967212 -0.0695663  -0.10615081  0.0656138   0.00494081  0.00842735
   0.04417142 -0.10535145  0.10190911 -0.02211629  0.03785806  0.09518665
  -0.03092178 -0.10188075]]

In [41]:
## Initializing the hidden layer of RNN

In [42]:
hidden_size=32

W_xh = np.random.randn(32, 32) / np.sqrt(32)
W_hh = np.random.randn(32, 32) / np.sqrt(32)
b_h = np.zeros(32)


print("W_xh:", W_xh.shape)
print("W_hh:", W_hh.shape)
print("b_h:", b_h.shape)

W_xh: (32, 32)
W_hh: (32, 32)
b_h: (32,)

In [43]:
## initializing the output layer of RNN

In [44]:
output_size=2

W_yh=np.random.randn(2,32) / np.sqrt(32)
b_y=np.zeros(2,)

print("W_yh:", W_yh.shape)
print("b_y:", b_y.shape)

W_yh: (2, 32)
b_y: (2,)

In [45]:
## first hidden state calculation 

h = np.zeros(hidden_size)

x_1 = E[X_train_array[0][0]]

h_1 = np.tanh(
    W_xh @ x_1
    + W_hh @ h
    + b_h
)

print("x_1 shape:", x_1.shape)
print("h_1 shape:", h_1.shape)

x_1 shape: (32,)
h_1 shape: (32,)

In [46]:
## Second hidden state calculation

x_2 = E[X_train_array[0][1]]

h_2 = np.tanh(W_xh @ x_2+ W_hh @ h_1+ b_h)

print("x_2 shape:", x_2.shape)
print("h_2 shape:", h_2.shape)

x_2 shape: (32,)
h_2 shape: (32,)

In [47]:
def forward_pass(token_ids):
    h = np.zeros(hidden_size)
    processed_token_ids = []
    
    hidden_states = [h.copy()]
    embeddings = []

    for t in range(len(token_ids)):
        token_id = token_ids[t]

        if token_id == PAD_ID:
            continue
            
        processed_token_ids.append(token_id)
        
        x_t = E[token_id]
        embeddings.append(x_t.copy())

        h = np.tanh(
            W_xh @ x_t
            + W_hh @ h
            + b_h
        )

        hidden_states.append(h.copy())

    logits = W_yh @ h + b_y

    cache = {
    "hidden_states": hidden_states,
    "embeddings": embeddings,
    "token_ids": processed_token_ids
}
    return h, logits, cache

In [48]:
final_hidden, logits, cache = forward_pass(X_train_array[0])

print("Token IDs:", len(cache["token_ids"]))
print("Embeddings:", len(cache["embeddings"]))
print("Hidden states:", len(cache["hidden_states"]))

Token IDs: 100
Embeddings: 100
Hidden states: 101

In [49]:
def softmax(logits):
    exp_values = np.exp(logits - np.max(logits))
    probabilities = exp_values / np.sum(exp_values)
    return probabilities

In [50]:
probabilities = softmax(logits)

print("Probabilities:", probabilities)
print("Sum of probabilities:", np.sum(probabilities))

Probabilities: [0.5525282 0.4474718]
Sum of probabilities: 1.0

In [51]:
def calculate_loss(probabilities, true_label):
    loss = -np.log(probabilities[true_label])
    return loss

In [52]:
true_label=1

y_one_hot=np.zeros(output_size)
y_one_hot[true_label]=1
delta_z=probabilities-y_one_hot
print("Delta z :",delta_z)

Delta z : [ 0.5525282 -0.5525282]

In [53]:
def backward_pass(cache,delta_z):
    hidden_states=cache['hidden_states']
    embeddings=cache['embeddings']
    token_ids=cache['token_ids']

    ## weight ,bias & embedding grad matrix initialization
    dW_yh = np.zeros_like(W_yh)
    db_y = np.zeros_like(b_y)

    dW_xh = np.zeros_like(W_xh)
    dW_hh = np.zeros_like(W_hh)
    db_h = np.zeros_like(b_h)

    dE = np.zeros_like(E)

    # grad for loss wrt output params 
    dW_yh=np.outer(delta_z,hidden_states[-1])
    db_yh=delta_z.copy()
    dh=W_yh.T @ delta_z ## this calculate the loss wrt last hidden state 

    for t in reversed(range(len(embeddings))):
        h_t=hidden_states[t+1]
        h_prev=hidden_states[t]
        x_t=embeddings[t]
        token_id=token_ids[t]

        # moving backward from tanh
        da = dh * (1 - h_t**2)

        # Accumulate hidden-layer parameter gradients(they are adding because in the mathematical derivation we have summation for it at every timestep
        dW_xh += np.outer(da, x_t)
        dW_hh += np.outer(da, h_prev)
        db_h += da

        # Calculate and accumulate embedding grads
        dx = W_xh.T @ da
        dE[token_id] += dx

        # Prop grad to the previous hidden state
        dh = W_hh.T @ da ## just like as we did it outside the loop for the final hidden layer
        
    return dW_yh, db_yh, dW_xh, dW_hh, db_h,dE

In [54]:
def update_parameters(dW_yh, db_y,dW_xh, dW_hh, db_h,dE,learning_rate):
    # Update output-layer parameters
    W_yh[:] -= learning_rate * dW_yh
    b_y[:]  -= learning_rate * db_y

    # Update hidden-layer parameters
    W_xh[:] -= learning_rate * dW_xh
    W_hh[:] -= learning_rate * dW_hh
    b_h[:]  -= learning_rate * db_h

    # Update embedding matrix
    E[:] -= learning_rate * dE

    # Keep padding embedding fixed at zero
    E[PAD_ID] = 0

In [55]:
print("Original labels:")
print(df["sentiment"].value_counts(dropna=False))

print("\nMissing labels:", df["sentiment"].isna().sum())
print("Training label values:", np.unique(y_train_array))

Original labels:
sentiment
1    25000
0    25000
Name: count, dtype: int64

Missing labels: 0
Training label values: [-9223372036854775808]

In [56]:
print("y_train sample:")
print(y_train[:10])

print("\nTraining labels' dtype:", y_train.dtype)
print("Training labels' unique values:", np.unique(y_train))

y_train sample:
47808   NaN
20154   NaN
43069   NaN
19413   NaN
13673   NaN
40368   NaN
15432   NaN
10208   NaN
42345   NaN
42141   NaN
Name: sentiment, dtype: float64

Training labels' dtype: float64
Training labels' unique values: [nan]

In [57]:
print("Training DataFrame labels:")
print(train_df["sentiment"].head(10))

print("\nTraining DataFrame unique labels:")
print(train_df["sentiment"].unique())

print("\nCurrent y_train:")
print(y_train.head(10))

Training DataFrame labels:
47808    1
20154    0
43069    0
19413    0
13673    0
40368    1
15432    1
10208    1
42345    1
42141    1
Name: sentiment, dtype: int64

Training DataFrame unique labels:
[1 0]

Current y_train:
47808   NaN
20154   NaN
43069   NaN
19413   NaN
13673   NaN
40368   NaN
15432   NaN
10208   NaN
42345   NaN
42141   NaN
Name: sentiment, dtype: float64

In [58]:
# Recreate labels from the original split DataFrames
y_train = train_df["sentiment"].copy()
y_val = val_df["sentiment"].copy()
y_test = test_df["sentiment"].copy()

# Convert labels into NumPy arrays
y_train_array = y_train.to_numpy(dtype=np.int64)
y_val_array = y_val.to_numpy(dtype=np.int64)
y_test_array = y_test.to_numpy(dtype=np.int64)

In [59]:
print("Training labels:", np.unique(y_train_array))
print("Validation labels:", np.unique(y_val_array))
print("Test labels:", np.unique(y_test_array))

print("\nTraining shape:", y_train_array.shape)
print("Validation shape:", y_val_array.shape)
print("Test shape:", y_test_array.shape)

print("\nAny invalid training labels:", 
      not np.isin(y_train_array, [0, 1]).all())

print("Any NaN values in training labels:", 
      np.isnan(y_train_array).any())

Training labels: [0 1]
Validation labels: [0 1]
Test labels: [0 1]

Training shape: (40000,)
Validation shape: (5000,)
Test shape: (5000,)

Any invalid training labels: False
Any NaN values in training labels: False

In [61]:
print("Validation shape:", X_val_array.shape)
print("Validation data type:", X_val_array.dtype)
print("First review token IDs:", X_val_array[0][:10])

Validation shape: (5000, 100)
Validation data type: int64
First review token IDs: [  204    22     2   530   411     4   397 10001    60   264]

In [62]:
## review test Done the programme worked properly

In [63]:
## Starting the training

In [ ]:
import time
import numpy as np
# Set how many times we want the model to go through the dataset
epochs = 10
learning_rate = 0.01

# Keep the results from each epoch so we can check them later
train_losses = []
train_accuracies = []
val_losses = []
val_accuracies = []

# Keep track of the total training time
training_start_time = time.time()

# Start Training
for epoch in range(epochs):

    # Start timing this epoch and reset the metrics
    epoch_start_time = time.time()
    total_train_loss = 0.0
    correct_predictions = 0

    # Shuffle the reviews so the model doesn't see them in the same order every time
    indices = np.random.permutation(len(X_train_array))

    # Go through each training review one by one
    for step, i in enumerate(indices, start=1):

        # Get the current review and its actual label
        token_ids = X_train_array[i]
        true_label = int(y_train_array[i])

        # Pass the review through the RNN and get the prediction
        final_hidden, logits, cache = forward_pass(token_ids)

        # Convert the logits into probabilities
        probabilities = softmax(logits)

        # Calculate how wrong the prediction is
        loss = calculate_loss(probabilities, true_label)
        total_train_loss += loss

        # Check whether the prediction is correct
        predicted_label = np.argmax(probabilities)

        if predicted_label == true_label:
            correct_predictions += 1

        # Calculate the gradient of the loss with respect to the logits
        delta_z = probabilities.copy()
        delta_z[true_label] -= 1

        # Run backpropagation and calculate all the gradients
        dW_yh, db_y, dW_xh, dW_hh, db_h, dE = backward_pass(cache, delta_z)

        # Clip gradients: if the total gradient size is above 5, scale everything down
        total_norm = np.sqrt(np.sum(dW_yh**2) + np.sum(db_y**2) + np.sum(dW_xh**2)+ np.sum(dW_hh**2) + np.sum(db_h**2) + np.sum(dE**2))
        if total_norm > 5.0:
            scale = 5.0 / total_norm
            dW_yh *= scale
            db_y *= scale
            dW_xh *= scale
            dW_hh *= scale
            db_h *= scale
            dE *= scale
        

        # Use the gradients to update all the model parameters
        update_parameters(dW_yh, db_y,dW_xh, dW_hh, db_h,dE, learning_rate)

        # Show how far we've got every 1000 reviews
        if step % 1000 == 0:
            elapsed = time.time() - epoch_start_time

            print(
                f"Epoch {epoch + 1}/{epochs} | "
                f"Reviews: {step}/{len(X_train_array)} | "
                f"Current Loss: {loss:.4f} | "
                f"Time: {elapsed / 60:.2f} min",
                flush=True)

    # Calculate the average training loss for this epoch
    avg_train_loss = total_train_loss / len(X_train_array)

    # Calculate training accuracy as a percentage
    train_accuracy = (correct_predictions / len(X_train_array)) * 100

    # Save the training results so we can check them later
    train_losses.append(avg_train_loss)
    train_accuracies.append(train_accuracy)

    # Check how the model performs on validation reviews
    total_val_loss = 0.0
    correct_val_predictions = 0

    # Go through the validation reviews without updating the weights
    for i in range(len(X_val_array)):

        # Get the current validation review and its actual label
        token_ids = X_val_array[i]
        true_label = int(y_val_array[i])

        # Get the model's prediction for this review
        final_hidden, logits, cache = forward_pass(token_ids)

        # Convert the logits into probabilities
        probabilities = softmax(logits)

        # Calculate the validation loss
        loss = calculate_loss(probabilities, true_label)
        total_val_loss += loss

        # Check whether the validation prediction is correct
        predicted_label = np.argmax(probabilities)

        if predicted_label == true_label:
            correct_val_predictions += 1

    # Calculate the average validation loss and accuracy
    avg_val_loss = total_val_loss / len(X_val_array)

    val_accuracy = (correct_val_predictions / len(X_val_array)) * 100

    # Save the validation results so we can check them later
    val_losses.append(avg_val_loss)
    val_accuracies.append(val_accuracy)

    # Calculate how long this epoch took
    epoch_time = time.time() - epoch_start_time

    # Calculate the total time spent training so far
    elapsed_time = time.time() - training_start_time

    # Print all the results after this epoch finishes
    print(
        f"\nEpoch {epoch + 1}/{epochs} completed | "
        f"Train Loss: {avg_train_loss:.4f} | "
        f"Train Accuracy: {train_accuracy:.2f}% | "
        f"Val Loss: {avg_val_loss:.4f} | "
        f"Val Accuracy: {val_accuracy:.2f}% | "
        f"Epoch Time: {epoch_time / 60:.2f} min | "
        f"Total Time: {elapsed_time / 60:.2f} min\n",
        flush=True
    )

Epoch 1/10 | Reviews: 1000/40000 | Current Loss: 0.5558 | Time: 0.31 min
Epoch 1/10 | Reviews: 2000/40000 | Current Loss: 0.7301 | Time: 0.63 min
Epoch 1/10 | Reviews: 3000/40000 | Current Loss: 0.4028 | Time: 0.89 min
Epoch 1/10 | Reviews: 4000/40000 | Current Loss: 0.7748 | Time: 1.15 min
Epoch 1/10 | Reviews: 5000/40000 | Current Loss: 0.6477 | Time: 1.48 min
Epoch 1/10 | Reviews: 6000/40000 | Current Loss: 1.0668 | Time: 1.79 min
Epoch 1/10 | Reviews: 7000/40000 | Current Loss: 0.5365 | Time: 2.09 min
Epoch 1/10 | Reviews: 8000/40000 | Current Loss: 0.5785 | Time: 2.45 min
Epoch 1/10 | Reviews: 9000/40000 | Current Loss: 0.8242 | Time: 2.81 min
Epoch 1/10 | Reviews: 10000/40000 | Current Loss: 0.6193 | Time: 3.17 min
Epoch 1/10 | Reviews: 11000/40000 | Current Loss: 0.6336 | Time: 3.52 min
Epoch 1/10 | Reviews: 12000/40000 | Current Loss: 0.6230 | Time: 3.87 min
Epoch 1/10 | Reviews: 13000/40000 | Current Loss: 0.5710 | Time: 4.22 min
Epoch 1/10 | Reviews: 14000/40000 | Current Loss: 0.5902 | Time: 4.57 min
Epoch 1/10 | Reviews: 15000/40000 | Current Loss: 0.7839 | Time: 4.92 min
Epoch 1/10 | Reviews: 16000/40000 | Current Loss: 0.6316 | Time: 5.28 min
Epoch 1/10 | Reviews: 17000/40000 | Current Loss: 0.7278 | Time: 5.63 min
Epoch 1/10 | Reviews: 18000/40000 | Current Loss: 0.8539 | Time: 5.98 min
Epoch 1/10 | Reviews: 19000/40000 | Current Loss: 0.9268 | Time: 6.33 min
Epoch 1/10 | Reviews: 20000/40000 | Current Loss: 0.9606 | Time: 6.69 min
Epoch 1/10 | Reviews: 21000/40000 | Current Loss: 0.9918 | Time: 7.04 min
Epoch 1/10 | Reviews: 22000/40000 | Current Loss: 0.9296 | Time: 7.39 min
Epoch 1/10 | Reviews: 23000/40000 | Current Loss: 0.7410 | Time: 7.75 min
Epoch 1/10 | Reviews: 24000/40000 | Current Loss: 1.1648 | Time: 8.10 min
Epoch 1/10 | Reviews: 25000/40000 | Current Loss: 0.7500 | Time: 8.46 min
Epoch 1/10 | Reviews: 26000/40000 | Current Loss: 0.8317 | Time: 8.82 min
Epoch 1/10 | Reviews: 27000/40000 | Current Loss: 1.1359 | Time: 9.18 min
Epoch 1/10 | Reviews: 28000/40000 | Current Loss: 0.3543 | Time: 9.54 min
Epoch 1/10 | Reviews: 29000/40000 | Current Loss: 0.6278 | Time: 9.89 min
Epoch 1/10 | Reviews: 30000/40000 | Current Loss: 1.1441 | Time: 10.24 min
Epoch 1/10 | Reviews: 31000/40000 | Current Loss: 0.6791 | Time: 10.59 min
Epoch 1/10 | Reviews: 32000/40000 | Current Loss: 0.9541 | Time: 10.90 min
Epoch 1/10 | Reviews: 33000/40000 | Current Loss: 0.8639 | Time: 11.23 min
Epoch 1/10 | Reviews: 34000/40000 | Current Loss: 0.7365 | Time: 11.54 min
Epoch 1/10 | Reviews: 35000/40000 | Current Loss: 0.6099 | Time: 11.89 min
Epoch 1/10 | Reviews: 36000/40000 | Current Loss: 0.8189 | Time: 12.22 min
Epoch 1/10 | Reviews: 37000/40000 | Current Loss: 0.5623 | Time: 12.57 min
Epoch 1/10 | Reviews: 38000/40000 | Current Loss: 0.5873 | Time: 12.92 min
Epoch 1/10 | Reviews: 39000/40000 | Current Loss: 0.9688 | Time: 13.28 min
Epoch 1/10 | Reviews: 40000/40000 | Current Loss: 0.5843 | Time: 13.63 min

Epoch 1/10 completed | Train Loss: 0.7142 | Train Accuracy: 50.06% | Val Loss: 0.7008 | Val Accuracy: 48.58% | Epoch Time: 13.94 min | Total Time: 13.94 min

Epoch 2/10 | Reviews: 1000/40000 | Current Loss: 0.4340 | Time: 0.35 min
Epoch 2/10 | Reviews: 2000/40000 | Current Loss: 0.4823 | Time: 0.71 min
Epoch 2/10 | Reviews: 3000/40000 | Current Loss: 0.6379 | Time: 1.07 min
Epoch 2/10 | Reviews: 4000/40000 | Current Loss: 0.7410 | Time: 1.42 min
Epoch 2/10 | Reviews: 5000/40000 | Current Loss: 0.7170 | Time: 1.77 min
Epoch 2/10 | Reviews: 6000/40000 | Current Loss: 0.8587 | Time: 2.12 min
Epoch 2/10 | Reviews: 7000/40000 | Current Loss: 0.9031 | Time: 2.44 min
Epoch 2/10 | Reviews: 8000/40000 | Current Loss: 1.0688 | Time: 2.75 min
Epoch 2/10 | Reviews: 9000/40000 | Current Loss: 0.7741 | Time: 3.11 min
Epoch 2/10 | Reviews: 10000/40000 | Current Loss: 0.9159 | Time: 3.47 min
Epoch 2/10 | Reviews: 11000/40000 | Current Loss: 0.4761 | Time: 3.82 min
Epoch 2/10 | Reviews: 12000/40000 | Current Loss: 0.8169 | Time: 4.18 min
Epoch 2/10 | Reviews: 13000/40000 | Current Loss: 0.6520 | Time: 4.53 min
Epoch 2/10 | Reviews: 14000/40000 | Current Loss: 1.0114 | Time: 4.90 min
Epoch 2/10 | Reviews: 15000/40000 | Current Loss: 0.9070 | Time: 5.26 min
Epoch 2/10 | Reviews: 16000/40000 | Current Loss: 0.7997 | Time: 5.62 min
Epoch 2/10 | Reviews: 17000/40000 | Current Loss: 0.6312 | Time: 5.98 min
Epoch 2/10 | Reviews: 18000/40000 | Current Loss: 0.5438 | Time: 6.33 min
Epoch 2/10 | Reviews: 19000/40000 | Current Loss: 0.6681 | Time: 6.69 min
Epoch 2/10 | Reviews: 20000/40000 | Current Loss: 0.5389 | Time: 7.05 min
Epoch 2/10 | Reviews: 21000/40000 | Current Loss: 0.7929 | Time: 7.40 min
Epoch 2/10 | Reviews: 22000/40000 | Current Loss: 0.8412 | Time: 7.76 min
Epoch 2/10 | Reviews: 23000/40000 | Current Loss: 0.9539 | Time: 8.12 min
Epoch 2/10 | Reviews: 24000/40000 | Current Loss: 0.4244 | Time: 8.48 min
Epoch 2/10 | Reviews: 25000/40000 | Current Loss: 0.8962 | Time: 8.83 min
Epoch 2/10 | Reviews: 26000/40000 | Current Loss: 0.8955 | Time: 9.18 min
Epoch 2/10 | Reviews: 27000/40000 | Current Loss: 0.6129 | Time: 9.52 min
Epoch 2/10 | Reviews: 28000/40000 | Current Loss: 0.7528 | Time: 9.87 min
Epoch 2/10 | Reviews: 29000/40000 | Current Loss: 0.8975 | Time: 10.24 min
Epoch 2/10 | Reviews: 30000/40000 | Current Loss: 0.8766 | Time: 10.60 min
Epoch 2/10 | Reviews: 31000/40000 | Current Loss: 0.5832 | Time: 10.96 min
Epoch 2/10 | Reviews: 32000/40000 | Current Loss: 0.9822 | Time: 11.32 min
Epoch 2/10 | Reviews: 33000/40000 | Current Loss: 0.6062 | Time: 11.67 min
Epoch 2/10 | Reviews: 34000/40000 | Current Loss: 0.5498 | Time: 12.03 min
Epoch 2/10 | Reviews: 35000/40000 | Current Loss: 0.8672 | Time: 12.39 min
Epoch 2/10 | Reviews: 36000/40000 | Current Loss: 0.8713 | Time: 12.75 min
Epoch 2/10 | Reviews: 37000/40000 | Current Loss: 0.9604 | Time: 13.11 min
Epoch 2/10 | Reviews: 38000/40000 | Current Loss: 0.6241 | Time: 13.46 min
Epoch 2/10 | Reviews: 39000/40000 | Current Loss: 0.7491 | Time: 13.81 min
Epoch 2/10 | Reviews: 40000/40000 | Current Loss: 1.1540 | Time: 14.17 min

Epoch 2/10 completed | Train Loss: 0.7088 | Train Accuracy: 51.00% | Val Loss: 0.6850 | Val Accuracy: 57.00% | Epoch Time: 14.47 min | Total Time: 28.42 min

Epoch 3/10 | Reviews: 1000/40000 | Current Loss: 0.4921 | Time: 0.37 min
Epoch 3/10 | Reviews: 2000/40000 | Current Loss: 1.0286 | Time: 0.72 min
Epoch 3/10 | Reviews: 3000/40000 | Current Loss: 0.5955 | Time: 1.07 min
Epoch 3/10 | Reviews: 4000/40000 | Current Loss: 0.7332 | Time: 1.42 min
Epoch 3/10 | Reviews: 5000/40000 | Current Loss: 0.6367 | Time: 1.77 min
Epoch 3/10 | Reviews: 6000/40000 | Current Loss: 0.7589 | Time: 2.13 min
Epoch 3/10 | Reviews: 7000/40000 | Current Loss: 1.0906 | Time: 2.48 min
Epoch 3/10 | Reviews: 8000/40000 | Current Loss: 0.4543 | Time: 2.83 min
Epoch 3/10 | Reviews: 9000/40000 | Current Loss: 0.7673 | Time: 3.18 min
Epoch 3/10 | Reviews: 10000/40000 | Current Loss: 1.0788 | Time: 3.54 min
Epoch 3/10 | Reviews: 11000/40000 | Current Loss: 0.4309 | Time: 3.88 min
Epoch 3/10 | Reviews: 12000/40000 | Current Loss: 0.4640 | Time: 4.23 min
Epoch 3/10 | Reviews: 13000/40000 | Current Loss: 0.7224 | Time: 4.58 min
Epoch 3/10 | Reviews: 14000/40000 | Current Loss: 0.4338 | Time: 4.93 min
Epoch 3/10 | Reviews: 15000/40000 | Current Loss: 0.7878 | Time: 5.29 min
Epoch 3/10 | Reviews: 16000/40000 | Current Loss: 0.5788 | Time: 5.63 min
Epoch 3/10 | Reviews: 17000/40000 | Current Loss: 1.0261 | Time: 5.98 min
Epoch 3/10 | Reviews: 18000/40000 | Current Loss: 0.4844 | Time: 6.35 min
Epoch 3/10 | Reviews: 19000/40000 | Current Loss: 0.6986 | Time: 6.70 min
Epoch 3/10 | Reviews: 20000/40000 | Current Loss: 0.5067 | Time: 7.05 min
Epoch 3/10 | Reviews: 21000/40000 | Current Loss: 0.5479 | Time: 7.40 min
Epoch 3/10 | Reviews: 22000/40000 | Current Loss: 0.4794 | Time: 7.74 min
Epoch 3/10 | Reviews: 23000/40000 | Current Loss: 0.7040 | Time: 8.10 min
Epoch 3/10 | Reviews: 24000/40000 | Current Loss: 0.6202 | Time: 8.45 min
Epoch 3/10 | Reviews: 25000/40000 | Current Loss: 0.5832 | Time: 8.80 min
Epoch 3/10 | Reviews: 26000/40000 | Current Loss: 0.5195 | Time: 9.15 min
Epoch 3/10 | Reviews: 27000/40000 | Current Loss: 0.7200 | Time: 9.50 min
Epoch 3/10 | Reviews: 28000/40000 | Current Loss: 0.4547 | Time: 9.85 min
Epoch 3/10 | Reviews: 29000/40000 | Current Loss: 0.7628 | Time: 10.21 min
Epoch 3/10 | Reviews: 30000/40000 | Current Loss: 0.5641 | Time: 10.57 min
Epoch 3/10 | Reviews: 31000/40000 | Current Loss: 0.6228 | Time: 10.92 min
Epoch 3/10 | Reviews: 32000/40000 | Current Loss: 0.2587 | Time: 11.27 min
Epoch 3/10 | Reviews: 33000/40000 | Current Loss: 0.7872 | Time: 11.62 min
Epoch 3/10 | Reviews: 34000/40000 | Current Loss: 0.7314 | Time: 11.98 min
Epoch 3/10 | Reviews: 35000/40000 | Current Loss: 0.5037 | Time: 12.34 min
Epoch 3/10 | Reviews: 36000/40000 | Current Loss: 0.4679 | Time: 12.68 min
Epoch 3/10 | Reviews: 37000/40000 | Current Loss: 0.7395 | Time: 13.02 min
Epoch 3/10 | Reviews: 38000/40000 | Current Loss: 0.4731 | Time: 13.38 min
Epoch 3/10 | Reviews: 39000/40000 | Current Loss: 0.5984 | Time: 13.74 min
Epoch 3/10 | Reviews: 40000/40000 | Current Loss: 0.5352 | Time: 14.09 min

Epoch 3/10 completed | Train Loss: 0.6916 | Train Accuracy: 55.78% | Val Loss: 0.6980 | Val Accuracy: 54.02% | Epoch Time: 14.41 min | Total Time: 42.83 min

Epoch 4/10 | Reviews: 1000/40000 | Current Loss: 0.9754 | Time: 0.39 min
Epoch 4/10 | Reviews: 2000/40000 | Current Loss: 0.9540 | Time: 0.76 min
Epoch 4/10 | Reviews: 3000/40000 | Current Loss: 0.3866 | Time: 1.12 min
Epoch 4/10 | Reviews: 4000/40000 | Current Loss: 0.3364 | Time: 1.48 min
Epoch 4/10 | Reviews: 5000/40000 | Current Loss: 0.1963 | Time: 1.84 min
Epoch 4/10 | Reviews: 6000/40000 | Current Loss: 0.8939 | Time: 2.19 min
Epoch 4/10 | Reviews: 7000/40000 | Current Loss: 0.7112 | Time: 2.55 min
Epoch 4/10 | Reviews: 8000/40000 | Current Loss: 0.5472 | Time: 2.91 min
Epoch 4/10 | Reviews: 9000/40000 | Current Loss: 1.1476 | Time: 3.27 min
Epoch 4/10 | Reviews: 10000/40000 | Current Loss: 0.3319 | Time: 3.63 min
Epoch 4/10 | Reviews: 11000/40000 | Current Loss: 0.3881 | Time: 3.99 min
Epoch 4/10 | Reviews: 12000/40000 | Current Loss: 0.5597 | Time: 4.35 min
Epoch 4/10 | Reviews: 13000/40000 | Current Loss: 0.6704 | Time: 4.72 min
Epoch 4/10 | Reviews: 14000/40000 | Current Loss: 0.9881 | Time: 5.08 min
Epoch 4/10 | Reviews: 15000/40000 | Current Loss: 0.6793 | Time: 5.45 min
Epoch 4/10 | Reviews: 16000/40000 | Current Loss: 0.5861 | Time: 5.81 min
Epoch 4/10 | Reviews: 17000/40000 | Current Loss: 0.3682 | Time: 6.18 min
Epoch 4/10 | Reviews: 18000/40000 | Current Loss: 0.4879 | Time: 6.55 min
Epoch 4/10 | Reviews: 19000/40000 | Current Loss: 0.4960 | Time: 6.91 min
Epoch 4/10 | Reviews: 20000/40000 | Current Loss: 1.3442 | Time: 7.28 min
Epoch 4/10 | Reviews: 21000/40000 | Current Loss: 1.1029 | Time: 7.64 min
Epoch 4/10 | Reviews: 22000/40000 | Current Loss: 1.2486 | Time: 8.00 min
Epoch 4/10 | Reviews: 23000/40000 | Current Loss: 1.0310 | Time: 8.36 min
Epoch 4/10 | Reviews: 24000/40000 | Current Loss: 0.5883 | Time: 8.73 min
Epoch 4/10 | Reviews: 25000/40000 | Current Loss: 0.7254 | Time: 9.02 min
Epoch 4/10 | Reviews: 26000/40000 | Current Loss: 0.0870 | Time: 9.30 min
Epoch 4/10 | Reviews: 27000/40000 | Current Loss: 0.3381 | Time: 9.57 min
Epoch 4/10 | Reviews: 28000/40000 | Current Loss: 0.4388 | Time: 9.80 min
Epoch 4/10 | Reviews: 29000/40000 | Current Loss: 0.8874 | Time: 10.03 min
Epoch 4/10 | Reviews: 30000/40000 | Current Loss: 1.0289 | Time: 10.27 min
Epoch 4/10 | Reviews: 31000/40000 | Current Loss: 0.4919 | Time: 10.50 min
Epoch 4/10 | Reviews: 32000/40000 | Current Loss: 0.2511 | Time: 10.73 min
Epoch 4/10 | Reviews: 33000/40000 | Current Loss: 0.6595 | Time: 10.96 min
Epoch 4/10 | Reviews: 34000/40000 | Current Loss: 0.3973 | Time: 11.20 min
Epoch 4/10 | Reviews: 35000/40000 | Current Loss: 0.2347 | Time: 11.43 min
Epoch 4/10 | Reviews: 36000/40000 | Current Loss: 0.6874 | Time: 11.64 min
Epoch 4/10 | Reviews: 37000/40000 | Current Loss: 0.4454 | Time: 11.85 min
Epoch 4/10 | Reviews: 38000/40000 | Current Loss: 1.0512 | Time: 12.09 min
Epoch 4/10 | Reviews: 39000/40000 | Current Loss: 0.9564 | Time: 12.33 min
Epoch 4/10 | Reviews: 40000/40000 | Current Loss: 0.9012 | Time: 12.56 min

Epoch 4/10 completed | Train Loss: 0.6874 | Train Accuracy: 59.16% | Val Loss: 0.6349 | Val Accuracy: 64.98% | Epoch Time: 12.76 min | Total Time: 55.59 min

Epoch 5/10 | Reviews: 1000/40000 | Current Loss: 0.8455 | Time: 0.23 min
Epoch 5/10 | Reviews: 2000/40000 | Current Loss: 0.5078 | Time: 0.46 min
Epoch 5/10 | Reviews: 3000/40000 | Current Loss: 0.4466 | Time: 0.69 min
Epoch 5/10 | Reviews: 4000/40000 | Current Loss: 0.6315 | Time: 0.93 min
Epoch 5/10 | Reviews: 5000/40000 | Current Loss: 0.8186 | Time: 1.17 min
Epoch 5/10 | Reviews: 6000/40000 | Current Loss: 0.1998 | Time: 1.41 min
Epoch 5/10 | Reviews: 7000/40000 | Current Loss: 0.3406 | Time: 1.64 min
Epoch 5/10 | Reviews: 8000/40000 | Current Loss: 0.9033 | Time: 1.88 min
Epoch 5/10 | Reviews: 9000/40000 | Current Loss: 0.1377 | Time: 2.12 min
Epoch 5/10 | Reviews: 10000/40000 | Current Loss: 0.4492 | Time: 2.36 min
Epoch 5/10 | Reviews: 11000/40000 | Current Loss: 0.6786 | Time: 2.58 min
Epoch 5/10 | Reviews: 12000/40000 | Current Loss: 1.4254 | Time: 2.81 min
Epoch 5/10 | Reviews: 13000/40000 | Current Loss: 1.7118 | Time: 3.05 min
Epoch 5/10 | Reviews: 14000/40000 | Current Loss: 0.1214 | Time: 3.30 min
Epoch 5/10 | Reviews: 15000/40000 | Current Loss: 0.2321 | Time: 3.52 min
Epoch 5/10 | Reviews: 16000/40000 | Current Loss: 0.6233 | Time: 3.77 min
Epoch 5/10 | Reviews: 17000/40000 | Current Loss: 1.2546 | Time: 4.00 min
Epoch 5/10 | Reviews: 18000/40000 | Current Loss: 1.0393 | Time: 4.24 min
Epoch 5/10 | Reviews: 19000/40000 | Current Loss: 1.1755 | Time: 4.47 min
Epoch 5/10 | Reviews: 20000/40000 | Current Loss: 0.9800 | Time: 4.71 min
Epoch 5/10 | Reviews: 21000/40000 | Current Loss: 1.9980 | Time: 4.94 min
Epoch 5/10 | Reviews: 22000/40000 | Current Loss: 0.2061 | Time: 5.18 min
Epoch 5/10 | Reviews: 23000/40000 | Current Loss: 0.0811 | Time: 5.41 min
Epoch 5/10 | Reviews: 24000/40000 | Current Loss: 0.5309 | Time: 5.64 min
Epoch 5/10 | Reviews: 25000/40000 | Current Loss: 0.7673 | Time: 5.88 min
Epoch 5/10 | Reviews: 26000/40000 | Current Loss: 0.3565 | Time: 6.12 min
Epoch 5/10 | Reviews: 27000/40000 | Current Loss: 0.1242 | Time: 6.36 min
Epoch 5/10 | Reviews: 28000/40000 | Current Loss: 0.2173 | Time: 6.58 min
Epoch 5/10 | Reviews: 29000/40000 | Current Loss: 0.8457 | Time: 6.81 min
Epoch 5/10 | Reviews: 30000/40000 | Current Loss: 0.5660 | Time: 7.05 min
Epoch 5/10 | Reviews: 31000/40000 | Current Loss: 0.1656 | Time: 7.29 min
Epoch 5/10 | Reviews: 32000/40000 | Current Loss: 0.6109 | Time: 7.54 min
Epoch 5/10 | Reviews: 33000/40000 | Current Loss: 0.6022 | Time: 7.77 min
Epoch 5/10 | Reviews: 34000/40000 | Current Loss: 0.6275 | Time: 8.00 min
Epoch 5/10 | Reviews: 35000/40000 | Current Loss: 0.6791 | Time: 8.24 min
Epoch 5/10 | Reviews: 36000/40000 | Current Loss: 0.5188 | Time: 8.48 min
Epoch 5/10 | Reviews: 37000/40000 | Current Loss: 0.7961 | Time: 8.71 min
Epoch 5/10 | Reviews: 38000/40000 | Current Loss: 0.4075 | Time: 8.95 min
Epoch 5/10 | Reviews: 39000/40000 | Current Loss: 0.4564 | Time: 9.18 min
Epoch 5/10 | Reviews: 40000/40000 | Current Loss: 0.9877 | Time: 9.42 min

Epoch 5/10 completed | Train Loss: 0.6814 | Train Accuracy: 60.80% | Val Loss: 0.6594 | Val Accuracy: 60.12% | Epoch Time: 9.64 min | Total Time: 65.23 min

Epoch 6/10 | Reviews: 1000/40000 | Current Loss: 0.1182 | Time: 0.24 min
Epoch 6/10 | Reviews: 2000/40000 | Current Loss: 0.8400 | Time: 0.47 min
Epoch 6/10 | Reviews: 3000/40000 | Current Loss: 0.1071 | Time: 0.70 min
Epoch 6/10 | Reviews: 4000/40000 | Current Loss: 0.9135 | Time: 0.93 min
Epoch 6/10 | Reviews: 5000/40000 | Current Loss: 0.7735 | Time: 1.17 min
Epoch 6/10 | Reviews: 6000/40000 | Current Loss: 0.8920 | Time: 1.41 min
Epoch 6/10 | Reviews: 7000/40000 | Current Loss: 1.1795 | Time: 1.63 min
Epoch 6/10 | Reviews: 8000/40000 | Current Loss: 1.4323 | Time: 1.85 min
Epoch 6/10 | Reviews: 9000/40000 | Current Loss: 0.9909 | Time: 2.06 min
Epoch 6/10 | Reviews: 10000/40000 | Current Loss: 2.1674 | Time: 2.26 min
Epoch 6/10 | Reviews: 11000/40000 | Current Loss: 1.5158 | Time: 2.46 min
Epoch 6/10 | Reviews: 12000/40000 | Current Loss: 0.5174 | Time: 2.66 min
Epoch 6/10 | Reviews: 13000/40000 | Current Loss: 0.4090 | Time: 2.86 min
Epoch 6/10 | Reviews: 14000/40000 | Current Loss: 0.4048 | Time: 3.07 min
Epoch 6/10 | Reviews: 15000/40000 | Current Loss: 1.9787 | Time: 3.31 min
Epoch 6/10 | Reviews: 16000/40000 | Current Loss: 0.3177 | Time: 3.54 min
Epoch 6/10 | Reviews: 17000/40000 | Current Loss: 0.8287 | Time: 3.78 min
Epoch 6/10 | Reviews: 18000/40000 | Current Loss: 0.3509 | Time: 4.01 min
Epoch 6/10 | Reviews: 19000/40000 | Current Loss: 0.5194 | Time: 4.24 min
Epoch 6/10 | Reviews: 20000/40000 | Current Loss: 1.8369 | Time: 4.46 min
Epoch 6/10 | Reviews: 21000/40000 | Current Loss: 0.6343 | Time: 4.68 min
Epoch 6/10 | Reviews: 22000/40000 | Current Loss: 1.0288 | Time: 4.91 min
Epoch 6/10 | Reviews: 23000/40000 | Current Loss: 0.1616 | Time: 5.14 min
Epoch 6/10 | Reviews: 24000/40000 | Current Loss: 0.5452 | Time: 5.38 min
Epoch 6/10 | Reviews: 25000/40000 | Current Loss: 0.1961 | Time: 5.61 min
Epoch 6/10 | Reviews: 26000/40000 | Current Loss: 0.8894 | Time: 5.84 min
Epoch 6/10 | Reviews: 27000/40000 | Current Loss: 1.1659 | Time: 6.08 min
Epoch 6/10 | Reviews: 28000/40000 | Current Loss: 0.4719 | Time: 6.31 min
Epoch 6/10 | Reviews: 29000/40000 | Current Loss: 0.1897 | Time: 6.54 min
Epoch 6/10 | Reviews: 30000/40000 | Current Loss: 0.2097 | Time: 6.76 min
Epoch 6/10 | Reviews: 31000/40000 | Current Loss: 1.0838 | Time: 6.99 min
Epoch 6/10 | Reviews: 32000/40000 | Current Loss: 0.6717 | Time: 7.22 min
Epoch 6/10 | Reviews: 33000/40000 | Current Loss: 1.4136 | Time: 7.46 min
Epoch 6/10 | Reviews: 34000/40000 | Current Loss: 0.4857 | Time: 7.70 min
Epoch 6/10 | Reviews: 35000/40000 | Current Loss: 0.9480 | Time: 7.93 min
Epoch 6/10 | Reviews: 36000/40000 | Current Loss: 0.8960 | Time: 8.16 min
Epoch 6/10 | Reviews: 37000/40000 | Current Loss: 0.5174 | Time: 8.40 min
Epoch 6/10 | Reviews: 38000/40000 | Current Loss: 0.8387 | Time: 8.63 min
Epoch 6/10 | Reviews: 39000/40000 | Current Loss: 0.8135 | Time: 8.85 min
Epoch 6/10 | Reviews: 40000/40000 | Current Loss: 0.3779 | Time: 9.08 min

Epoch 6/10 completed | Train Loss: 0.6620 | Train Accuracy: 63.07% | Val Loss: 0.6628 | Val Accuracy: 60.72% | Epoch Time: 9.28 min | Total Time: 74.50 min

Epoch 7/10 | Reviews: 1000/40000 | Current Loss: 0.5680 | Time: 0.22 min
Epoch 7/10 | Reviews: 2000/40000 | Current Loss: 0.9457 | Time: 0.46 min
Epoch 7/10 | Reviews: 3000/40000 | Current Loss: 0.4565 | Time: 0.70 min
Epoch 7/10 | Reviews: 4000/40000 | Current Loss: 0.8681 | Time: 0.93 min
Epoch 7/10 | Reviews: 5000/40000 | Current Loss: 0.7650 | Time: 1.14 min
Epoch 7/10 | Reviews: 6000/40000 | Current Loss: 0.1692 | Time: 1.35 min
Epoch 7/10 | Reviews: 7000/40000 | Current Loss: 0.3530 | Time: 1.54 min
Epoch 7/10 | Reviews: 8000/40000 | Current Loss: 0.8890 | Time: 1.76 min
Epoch 7/10 | Reviews: 9000/40000 | Current Loss: 0.3846 | Time: 1.97 min
Epoch 7/10 | Reviews: 10000/40000 | Current Loss: 0.3061 | Time: 2.17 min
Epoch 7/10 | Reviews: 11000/40000 | Current Loss: 1.6884 | Time: 2.37 min
Epoch 7/10 | Reviews: 12000/40000 | Current Loss: 0.1282 | Time: 2.59 min
Epoch 7/10 | Reviews: 13000/40000 | Current Loss: 1.9768 | Time: 2.83 min
Epoch 7/10 | Reviews: 14000/40000 | Current Loss: 0.3433 | Time: 3.04 min
Epoch 7/10 | Reviews: 15000/40000 | Current Loss: 0.4709 | Time: 3.28 min
Epoch 7/10 | Reviews: 16000/40000 | Current Loss: 0.6184 | Time: 3.49 min
Epoch 7/10 | Reviews: 17000/40000 | Current Loss: 0.4538 | Time: 3.70 min