In [1]:
import numpy as np

print("NumPy version:", np.__version__)

NumPy version: 2.5.2

In [2]:
import pandas as pd

In [3]:
df = pd.read_csv("dataset/IMDB Dataset.csv")
df.head()

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [4]:
print(df.shape)
print(df.columns)

(50000, 2)
Index(['review', 'sentiment'], dtype='str')

In [5]:
df.sentiment.value_counts()

sentiment
positive    25000
negative    25000
Name: count, dtype: int64

In [6]:
df.isnull().sum()

review       0
sentiment    0
dtype: int64

In [7]:
df.sentiment=df.sentiment.map({"negative":0,"positive":1})
df.head()

                                              review  sentiment
0  One of the other reviewers has mentioned that ...          1
1  A wonderful little production. <br /><br />The...          1
2  I thought this was a wonderful way to spend ti...          1
3  Basically there's a family where a little boy ...          0
4  Petter Mattei's "Love in the Time of Money" is...          1

In [8]:
review1=df.review.iloc[0]
words=review1.lower().split()

print(words[:20])
print("Total words:", len(words))

['one', 'of', 'the', 'other', 'reviewers', 'has', 'mentioned', 'that', 'after', 'watching', 'just', '1', 'oz', 'episode', "you'll", 'be', 'hooked.', 'they', 'are', 'right,']
Total words: 307

In [9]:
word_counts={}

for review in df.review :
    words=review.lower().split()
    for word in words :
        if word in word_counts:
            word_counts[word]+=1
        else:
            word_counts[word]=1

print(list(word_counts.items())[:10]) ## dictionary does not support slicing so convert it into a list first & item make the pair as a tuple

[('one', 44983), ('of', 286661), ('the', 638861), ('other', 16373), ('reviewers', 418), ('has', 32610), ('mentioned', 810), ('that', 130140), ('after', 13948), ('watching', 8146)]

In [10]:
print(f"total unique wrds: {len(word_counts)}")

total unique wrds: 390931

In [11]:
unique_once=0
for word in word_counts:
    if word_counts[word]==1:
        unique_once+=1
print(unique_once)

237310

In [12]:
## Sorting the dictionary 

sorted_word_counts=sorted(word_counts.items(),key=lambda item :item[1],reverse=True)
print(sorted_word_counts[:50])

word_df=pd.DataFrame(sorted_word_counts,columns=["word","count"])

[('the', 638861), ('a', 316615), ('and', 313637), ('of', 286661), ('to', 264573), ('is', 204876), ('in', 179807), ('i', 141587), ('this', 138483), ('that', 130140), ('it', 129614), ('/><br', 100974), ('was', 93258), ('as', 88242), ('with', 84590), ('for', 84510), ('but', 77864), ('on', 62890), ('movie', 61492), ('are', 57009), ('his', 56870), ('not', 56765), ('you', 55600), ('film', 55086), ('have', 54423), ('he', 51062), ('be', 50901), ('at', 45259), ('one', 44983), ('by', 43359), ('an', 42330), ('they', 40860), ('from', 39322), ('all', 38570), ('who', 38326), ('like', 37281), ('so', 35972), ('just', 34259), ('or', 33300), ('has', 32610), ('about', 32398), ('her', 31244), ("it's", 31212), ('if', 30794), ('some', 30165), ('out', 28980), ('what', 28008), ('very', 26908), ('when', 26904), ('there', 26079)]

In [13]:
word_df.head(10)

   word   count
0   the  638861
1     a  316615
2   and  313637
3    of  286661
4    to  264573
5    is  204876
6    in  179807
7     i  141587
8  this  138483
9  that  130140

In [14]:
word_df.shape

(390931, 2)

In [15]:
## Taking vocab size of only 10000

In [16]:
top_words_df=word_df.head(10000)

print(f"Vocabulary size : {len(top_words_df)}")
print(top_words_df.head())
print(top_words_df.tail())

Vocabulary size : 10000
  word   count
0  the  638861
1    a  316615
2  and  313637
3   of  286661
4   to  264573
              word  count
9995      absorbed     69
9996      frontier     69
9997  representing     69
9998        paris.     69
9999       worked.     69

In [17]:
top_words_df["Token ID"]=range(1,len(top_words_df)+1)
print(top_words_df.head(10))
print(top_words_df.tail(10))

   word   count  Token ID
0   the  638861         1
1     a  316615         2
2   and  313637         3
3    of  286661         4
4    to  264573         5
5    is  204876         6
6    in  179807         7
7     i  141587         8
8  this  138483         9
9  that  130140        10
              word  count  Token ID
9990    consisting     69      9991
9991       shuttle     69      9992
9992      charlton     69      9993
9993         cecil     69      9994
9994       leader,     69      9995
9995      absorbed     69      9996
9996      frontier     69      9997
9997  representing     69      9998
9998        paris.     69      9999
9999       worked.     69     10000

In [18]:
word_to_id = {}

for i in range(len(top_words_df)):
    word = top_words_df.iloc[i]["word"]
    token_id = top_words_df.iloc[i]["Token ID"]

    word_to_id[word] = token_id

print(list(word_to_id.items())[:10])
print("Total words:", len(word_to_id))

[('the', np.int64(1)), ('a', np.int64(2)), ('and', np.int64(3)), ('of', np.int64(4)), ('to', np.int64(5)), ('is', np.int64(6)), ('in', np.int64(7)), ('i', np.int64(8)), ('this', np.int64(9)), ('that', np.int64(10))]
Total words: 10000

In [19]:
from sklearn.model_selection import train_test_split

In [20]:
train_df,temp_df=train_test_split(df,test_size=0.2,random_state=42,stratify=df["sentiment"])
val_df, test_df=train_test_split(temp_df,test_size=0.5,random_state=42,stratify=temp_df['sentiment'])

print("Training set:", train_df.shape)
print("Validation set:", val_df.shape)
print("Test set:", test_df.shape)

Training set: (40000, 2)
Validation set: (5000, 2)
Test set: (5000, 2)

In [21]:
X_train = train_df["review"]
y_train = train_df["sentiment"]

X_val = val_df["review"]
y_val = val_df["sentiment"]

X_test = test_df["review"]
y_test = test_df["sentiment"]

print("Training:", len(X_train), len(y_train))
print("Validation:", len(X_val), len(y_val))
print("Test:", len(X_test), len(y_test))

Training: 40000 40000
Validation: 5000 5000
Test: 5000 5000

In [22]:
## Doing all this for training Data frame

In [23]:
word_counts = {}

for review in X_train:
    words = review.lower().split()

    for word in words:
        if word in word_counts:
            word_counts[word] += 1
        else:
            word_counts[word] = 1

print("Unique words:", len(word_counts))

Unique words: 339686

In [24]:
sorted_words = sorted(
    word_counts.items(),
    key=lambda item: item[1],
    reverse=True
)

In [25]:
top_words_df = pd.DataFrame(
    sorted_words[:10000],
    columns=["word", "count"]
)

top_words_df["Token ID"] = range(
    1, len(top_words_df) + 1
)

print(top_words_df.head(10))
print("Vocabulary size:", len(top_words_df))

   word   count  Token ID
0   the  511759         1
1     a  253641         2
2   and  251160         3
3    of  229540         4
4    to  212085         5
5    is  163737         6
6    in  144054         7
7     i  113889         8
8  this  111137         9
9  that  104277        10
Vocabulary size: 10000

In [26]:
word_to_id = {}

for i in range(len(top_words_df)):
    word = top_words_df.iloc[i]["word"]
    token_id = top_words_df.iloc[i]["Token ID"]

    word_to_id[word] = token_id

print("Dictionary size:", len(word_to_id))
print(list(word_to_id.items())[:10])

Dictionary size: 10000
[('the', np.int64(1)), ('a', np.int64(2)), ('and', np.int64(3)), ('of', np.int64(4)), ('to', np.int64(5)), ('is', np.int64(6)), ('in', np.int64(7)), ('i', np.int64(8)), ('this', np.int64(9)), ('that', np.int64(10))]

In [27]:
PAD_ID = 0 #fills shorter reviews to a fixed length.
UNK_ID = 10001 ## represents words outside our 10,000-word vocabulary.

In [28]:
def review_to_ids(review):
    words=review.lower().split()
    token_ids=[]

    for word in words :
        if word in word_to_id:
            token_ids.append(word_to_id[word])
        else:
            token_ids.append(UNK_ID)
    return token_ids

In [29]:
print("Original review:")
print(X_train.iloc[0][:20])

Original review:
I caught this little

In [30]:
## Now testing it on one review 

print(review_to_ids(X_train.iloc[0][:20]))

[np.int64(8), np.int64(1014), np.int64(9), np.int64(106)]

In [31]:
X_train_ids=[]

for review in X_train:
    token_ids=review_to_ids(review)
    X_train_ids.append(token_ids)

print("Total reviews:", len(X_train_ids))
print("First review token IDs:", X_train_ids[0][:20])
print("First review length:", len(X_train_ids[0]))

Total reviews: 40000
First review token IDs: [np.int64(8), np.int64(1014), np.int64(9), np.int64(106), np.int64(2219), np.int64(393), np.int64(30), np.int64(2410), np.int64(153), np.int64(7), np.int64(9142), np.int64(39), 10001, np.int64(8), np.int64(13), np.int64(28), np.int64(2), 10001, np.int64(2160), np.int64(5)]
First review length: 161

In [32]:
## Restricting every review to 100 words max and padding words with length less than 100 words 

Max_len=100

X_train_padded = []

for token_ids in X_train_ids:
    if len(token_ids) > Max_len:
        token_ids = token_ids[:Max_len]
    else:
        while len(token_ids) < Max_len:
            token_ids.append(PAD_ID)

    X_train_padded.append(token_ids)

print("Total reviews:", len(X_train_padded))
print("First review:", X_train_padded[0])
print("First review length:", len(X_train_padded[0]))

Total reviews: 40000
First review: [np.int64(8), np.int64(1014), np.int64(9), np.int64(106), np.int64(2219), np.int64(393), np.int64(30), np.int64(2410), np.int64(153), np.int64(7), np.int64(9142), np.int64(39), 10001, np.int64(8), np.int64(13), np.int64(28), np.int64(2), 10001, np.int64(2160), np.int64(5), np.int64(65), np.int64(102), np.int64(174), np.int64(772), np.int64(1016), np.int64(559), np.int64(1), np.int64(2160), np.int64(13), np.int64(3698), np.int64(335), np.int64(3), np.int64(1663), np.int64(59), 10001, np.int64(32), np.int64(1162), np.int64(2), np.int64(711), np.int64(4), np.int64(1016), np.int64(384), 10001, np.int64(4045), np.int64(71), np.int64(190), np.int64(7), np.int64(1), 10001, np.int64(76), np.int64(66), np.int64(587), np.int64(1437), np.int64(17), np.int64(9), np.int64(323), np.int64(18), np.int64(482), np.int64(710), 10001, np.int64(1), np.int64(356), np.int64(13), np.int64(7), 10001, np.int64(1), np.int64(1020), np.int64(517), np.int64(323), np.int64(48), np.int64(32), np.int64(1162), 10001, 10001, np.int64(248), np.int64(563), 10001, 10001, np.int64(345), np.int64(4), np.int64(1596), np.int64(18), np.int64(43), np.int64(2984), np.int64(56), np.int64(263), np.int64(28), np.int64(1), np.int64(3765), np.int64(349), np.int64(2), np.int64(4220), np.int64(2461), np.int64(3), 10001, np.int64(10), np.int64(95), np.int64(11), np.int64(53), 10001]
First review length: 100

In [33]:
y_train = y_train.map({
    "negative": 0,
    "positive": 1
})

In [34]:
X_train_array = np.array(X_train_padded, dtype=np.int64)
y_train_array = np.array(y_train, dtype=np.int64)

print("X shape:", X_train_array.shape)
print("y shape:", y_train_array.shape)
print("X data type:", X_train_array.dtype)
print("y data type:", y_train_array.dtype)

X shape: (40000, 100)
y shape: (40000,)
X data type: int64
y data type: int64

C:\Users\HP\AppData\Roaming\Python\Python313\site-packages\pandas\core\series.py:901: RuntimeWarning: invalid value encountered in cast
  arr = np.array(values, dtype=dtype, copy=copy)

In [35]:
print("X_train_array:", X_train_array.shape)
print("y_train_array:", y_train_array.shape)

print("First 10 labels:", y_train_array[:10])
print("Unique labels:", np.unique(y_train_array))

X_train_array: (40000, 100)
y_train_array: (40000,)
First 10 labels: [-9223372036854775808 -9223372036854775808 -9223372036854775808
 -9223372036854775808 -9223372036854775808 -9223372036854775808
 -9223372036854775808 -9223372036854775808 -9223372036854775808
 -9223372036854775808]
Unique labels: [-9223372036854775808]

In [36]:
## intialize the embedding vector

In [37]:
embedding_size=32
vocab_size=10002

E=np.random.randn(vocab_size,embedding_size)*0.01

E[0]=0

print(f"Embedding matrix shape : {E.shape}")
print(f"Embedding of token ID 8 : {E[8]}")

Embedding matrix shape : (10002, 32)
Embedding of token ID 8 : [-1.09225744e-03 -2.39993710e-03 -6.41783256e-03 -7.83044516e-03
 -7.51181516e-03 -1.21173202e-02 -1.13783806e-02 -8.41979575e-03
 -2.75885845e-03 -6.40511355e-03  9.62663251e-03  1.70575554e-02
  1.76038755e-03 -2.12780891e-05  4.37532927e-03 -1.85816979e-02
 -1.54488364e-02 -7.55984806e-03 -4.90473066e-03  1.16990681e-02
 -1.28333237e-02  1.14625279e-03  3.13079185e-03  6.54020120e-03
  2.78859863e-03  8.36936225e-03  1.07106648e-02  2.56461301e-02
  1.61486919e-02  4.27094851e-03  6.18716722e-03 -2.19393634e-03]

In [38]:
token_ids = [8, 1014, 9, 106]

review_embeddings = E[token_ids]

print("Shape:", review_embeddings.shape)
print(review_embeddings)

Shape: (4, 32)
[[-1.09225744e-03 -2.39993710e-03 -6.41783256e-03 -7.83044516e-03
  -7.51181516e-03 -1.21173202e-02 -1.13783806e-02 -8.41979575e-03
  -2.75885845e-03 -6.40511355e-03  9.62663251e-03  1.70575554e-02
   1.76038755e-03 -2.12780891e-05  4.37532927e-03 -1.85816979e-02
  -1.54488364e-02 -7.55984806e-03 -4.90473066e-03  1.16990681e-02
  -1.28333237e-02  1.14625279e-03  3.13079185e-03  6.54020120e-03
   2.78859863e-03  8.36936225e-03  1.07106648e-02  2.56461301e-02
   1.61486919e-02  4.27094851e-03  6.18716722e-03 -2.19393634e-03]
 [-8.23927775e-03 -7.58188898e-03 -1.09900725e-02  1.65412691e-02
   3.39679757e-03  1.02097361e-02 -2.47190386e-03 -8.15265885e-03
   7.35845724e-03  1.24288997e-02 -7.67624851e-03 -7.45482849e-03
   1.75773917e-03  5.80333755e-03  2.01989065e-02 -4.25515004e-03
   7.05148434e-03  2.82355918e-03  2.64851018e-03  1.37570069e-03
  -1.13163453e-02 -1.03034584e-02  8.59347881e-03 -6.04594820e-03
   1.20531161e-02  4.60294774e-03 -2.73178162e-02  2.91714489e-03
   5.58321315e-03  3.10051238e-03  1.27129309e-02  9.17957396e-03]
 [ 4.40337826e-03  3.84776644e-03 -6.79735653e-03 -3.65211429e-03
  -8.99613746e-03  7.58747438e-03  4.90640896e-03  1.22669915e-02
  -1.81464993e-02  1.94276519e-03  1.97624302e-03 -1.03882928e-02
   6.69068066e-03 -1.43405739e-02  1.10211543e-02  2.88371685e-03
  -9.84750229e-05  2.12426431e-02 -6.09195093e-03 -9.96348363e-03
  -3.93541113e-03 -6.64523668e-03  1.90862627e-03  2.48349572e-03
  -2.85171293e-03  7.59964791e-03 -3.54626391e-03  3.69839170e-02
  -4.12138794e-03  1.38595858e-02  5.77404853e-03 -6.04462208e-03]
 [-1.58404790e-02 -5.23758374e-03  9.90804259e-03 -1.10286622e-02
  -2.70178625e-03  1.28347434e-03  6.67755713e-03 -1.67928026e-03
   2.05023774e-02 -3.86353706e-03 -1.59591725e-02 -1.57005927e-02
   1.06356979e-02  2.20751005e-03  8.25947226e-04  8.86228641e-03
   1.10922069e-02  3.18595513e-03 -9.15175664e-03  1.20082846e-02
   4.28974413e-03 -1.20225655e-02 -9.49651016e-03 -1.08645610e-02
   1.65088493e-02 -1.07062774e-03 -4.50669257e-03 -3.23177553e-03
  -1.60791331e-02  4.93751901e-04  9.39133585e-05  1.30506352e-02]]

In [39]:
## Initializing the hidden layer of RNN

In [40]:
hidden_size=32

W_xh = np.random.randn(32, 32) * 0.01
W_hh = np.random.randn(32, 32) * 0.01
b_h = np.zeros(32)


print("W_xh:", W_xh.shape)
print("W_hh:", W_hh.shape)
print("b_h:", b_h.shape)
print("h :" ,h.shape)

W_xh: (32, 32)
W_hh: (32, 32)
b_h: (32,)

NameError: name 'h' is not defined

In [ ]:
## initializing the output layer of RNN

In [ ]:
output_size=2

W_yh=np.random.randn(2,32)*0.01
b_y=np.zeros(2,)

print("W_yh:", W_yh.shape)
print("b_y:", b_y.shape)

In [ ]:
## first hidden state calculation 

h = np.zeros(hidden_size)

x_1 = E[X_train_array[0][0]]

h_1 = np.tanh(
    W_xh @ x_1
    + W_hh @ h
    + b_h
)

print("x_1 shape:", x_1.shape)
print("h_1 shape:", h_1.shape)

In [ ]:
## Second hidden state calculation

x_2 = E[X_train_array[0][1]]

h_2 = np.tanh(W_xh @ x_2+ W_hh @ h_1+ b_h)

print("x_2 shape:", x_2.shape)
print("h_2 shape:", h_2.shape)

In [ ]:
def forward_pass(token_ids):
    h = np.zeros(hidden_size)
    processed_token_ids = []
    
    hidden_states = [h.copy()]
    embeddings = []

    for t in range(len(token_ids)):
        token_id = token_ids[t]

        if token_id == PAD_ID:
            continue
            
        processed_token_ids.append(token_id)
        
        x_t = E[token_id]
        embeddings.append(x_t.copy())

        h = np.tanh(
            W_xh @ x_t
            + W_hh @ h
            + b_h
        )

        hidden_states.append(h.copy())

    logits = W_yh @ h + b_y

    cache = {
    "hidden_states": hidden_states,
    "embeddings": embeddings,
    "token_ids": processed_token_ids
}
    return h, logits, cache

In [ ]:
final_hidden, logits, cache = forward_pass(X_train_array[0])

print("Token IDs:", len(cache["token_ids"]))
print("Embeddings:", len(cache["embeddings"]))
print("Hidden states:", len(cache["hidden_states"]))

In [ ]:
def softmax(logits):
    exp_values = np.exp(logits - np.max(logits))
    probabilities = exp_values / np.sum(exp_values)
    return probabilities

In [ ]:
probabilities = softmax(logits)

print("Probabilities:", probabilities)
print("Sum of probabilities:", np.sum(probabilities))

In [ ]:
def calculate_loss(probabilities, true_label):
    loss = -np.log(probabilities[true_label])
    return loss

In [ ]:
true_label=1

y_one_hot=np.zeros(output_size)
y_one_hot[true_label]=1
delta_z=probabilities-y_one_hot
print("Delta z :",delta_z)

In [ ]:
def backward_pass(cache,delta_z):
    hidden_states=cache['hidden_states']
    embeddings=cache['embeddings']
    token_ids=cache['token_ids']

    ## weight ,bias & embedding grad matrix initialization
    dW_yh = np.zeros_like(W_yh)
    db_y = np.zeros_like(b_y)

    dW_xh = np.zeros_like(W_xh)
    dW_hh = np.zeros_like(W_hh)
    db_h = np.zeros_like(b_h)

    dE = np.zeros_like(E)

    # grad for loss wrt output params 
    dW_yh=np.outter(delta_z,hidden_states[-1])
    db_yh=delta_z.copy()
    dh=W_yh.T @ delta_z ## this calculate the loss wrt last hidden state 

    for t in reversed(range(len(embeddings)):
        h_t=hidden_states[t+1]
        h_prev=hidden_states[t]
        x_t=embeddings[t]
        token_id=toen_ids[t]

        # moving backward from tanh
        da = dh * (1 - h_t**2)

        # Accumulate hidden-layer parameter gradients(they are adding because in the mathematical derivation we have summation for it at every timestep
        dW_xh += np.outer(da, x_t)
        dW_hh += np.outer(da, h_prev)
        db_h += da

        # Calculate and accumulate embedding grads
        dx = W_xh.T @ da
        dE[token_id] += dx

        # Prop grad to the previous hidden state
        dh = W_hh.T @ da ## just like as we did it outside the loop for the final hidden layer
        
     return dW_yh, db_y, dW_xh, dW_hh, db_h, dE